// Common
export const CHOOSE_MOVE = 'CHOOSE_MOVE'

// Player
export const CHOOSE_NAME = 'CHOOSE_NAME'

// Game
export const ENABLE_UNDO_LAST_MOVE = 'ENABLE_UNDO_LAST_MOVE'
export const DISABLE_UNDO_LAST_MOVE = 'DISABLE_UNDO_LAST_MOVE'
export const NPC_START_PROCESSING = 'NPC_START_PROCESSING'
export const NPC_FINISH_PROCESSING = 'NPC_FINISH_PROCESSING'
export const END_GAME_WITH_WINNER = 'END_GAME_WITH_WINNER'
export const END_GAME_WITH_DRAW = 'END_GAME_WITH_DRAW'
